### PR TITLE
feat(logo): create logo and miniatures

### LINKED ISSUE #63: Logo Design Proposal for Pizza-sync
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo design for your project. If it's something you're interested in, please, let me know!

Best regards,
Ksenia

### PR DESCRIPTION
**Pull request by happyksu**
This closes #63

### CODE REVIEW

**Comment by maxime1992** [comment]
Hey @happyksu sorry for the delay I've been really busy this week.

I checked out your merge request and it's really great, good job! :clap: :clap: :clap: 

Few things to update before I can merge but love what you did :smile:!

Can you please:
- rename the folder `New_Logo` to simply `logo`
- remove the purple background of all the SVGs so it's easier to integrate them anywhere (and also crop the SVGs so they don't have huge margins) but keep the color on font + the pizza
- I don't know if it's just me or not but on pictures where there's only the pizza, it seems that the pizza's not centered (too much on the left) can you take a look and center it (if needed)?
- for the "complete logo" the one with the text + pizza, can you crop it a little bit on top and bottom so that the width is longer than the height? I'd prefer if the margins are closer to the text
- Update the README picture to point to the main repo (even though that'll not be working until we get everything merged)
- Rename your commits to follow the conventions
  - style(logo): create logo and miniatures
  - chore(logo): add logo on the readme

Thanks a lot!

**Comment by maxime1992** [comment]
I've spent some time updating the Readme because it was outdated.

I've added several screenshot of the app (how it'll be as soon as we get your logos merged :tada:).

I've also written your name at the end of the Readme to thank you for your work :+1: !

It's not updated on Master for now, I'm waiting your MR first but you can take a look [here](https://github.com/maxime1992/pizza-sync/blob/13a719384e985491df5348989e339e729b314c7b/README.md) in the meantime if you want to :smiley:

**Comment by happyksu** [comment]
Hi!
I have a lot of questions:)
1- I will change folder name, delete background in svg

2- It is centered.
>  don't know if it's just me or not but on pictures where there's only the pizza, it seems that the pizza's not centered (too much on the left)
image

3- Do you want all files cropped or only png?
> for the "complete logo" the one with the text + pizza, can you crop it a little bit

4- I thought that I updated readme. Or I did something wrong?

> Update the README picture to point to the main repo (even though that'll not be working until we get everything merged)

5- How to delete folder at github (without knowledge in coding)?

6- Should I create new merge request and name it "style(logo): create logo and miniatures"?

7- How can I do this?

> Please remove your commit where you were editing the README


And thank you for mentioning me! 😄

**Comment by maxime1992** [comment]
Hey there,

so if it's centered, nevermind. Perfect :+1: 

All files should be cropped to only contain the logo they embed (+ a very very small padding all around).

_Two exceptions:_
- _For icons (files named `PS_icon_*.png`). Those will be used probably to display the logo in a tab and thus, no CSS here. For the rest, I'll be able to set a background color. Image will be lighter and if I decide to change the theme it'll be easier too_
-_For the picture we will display on the README. Same problem I won't have any CSS on the README so can you please create one image especially for it, not cropped and with the background? The original logo used here though should be cropped and without background_

> I thought that I updated readme. Or I did something wrong?

Nothing that can't be fixed :smile_cat: 
You've set the image to point onto your repo. See [here](https://github.com/maxime1992/pizza-sync/pull/65/files#diff-04c6e90faac2675aa89e2176d2eec7d8). Forks might have a short life and an author of a fork might just remove it's copy once he does not plan to contribute anymore. So I'd rather prefer to have that link:  
`https://github.com/happyksu/pizza-sync/blob/master/New_Logo/png/PS_logo_low_res_2.png`  
to be  
`https://github.com/maxime1992/pizza-sync/...`
BUT, as explained I'll be updating the README right after we get your MR merged :raised_hands: 
So the simplest thing to do for now is just to remove that change on your side and I'll handle it :wink: 

> 5 - How to delete folder at github (without knowledge in coding)?
> 6 - Should I create new merge request and name it "style(logo): create logo and miniatures"?
> 7 - How can I do this?

So there's a way to modify existing commits with GIT.
It's totally fine IF:
- You're working in a branch, **your** branch and nobody else is working on it
- Your branch is **not** master and hasn't been merged in master yet
So it's a perfect match for merge request for example. You do something on a repo and a maintainer asks you to update your work, then instead of closing the MR and opening a new one, or simpler: Making the edits and creating a new commit (where the result if fine but you've got some unnecessary history in between), then you can edit your commits.

To do so, there's a git command caller `rebase`.

I've checked out your branch so I can show you exactly how to do it.
But let's figure out first, what we want to do exactly:
- Fix everything we discussed about, and create a new commit "WIP" (work in progress) for now
- Remove the commit which is updating the readme
- Rename your commit `Add files via upload` to `style(logo): create logo and miniatures`
- Merge the commit `style(logo): create logo and miniatures` with the `WIP` one so that we only have one commit, not one doing something and the other one fixing things from the previous one

For the 
> Fix everything we discussed about, and create a new commit "WIP" (work in progress) for now

I let you do that :smile: 

For the sake of the demo, I've also created a `WIP` commit so that we have the same history.

Here's what `git log` gives me:

image

These are the four last commits in your branch.
We want to edit 3 of them:

BEFORE GOING FURTHER: Please backup the whole pizza-sync folder in case you loose anything due to bad manipulation. But that should be fine, I'll explain step by step :smile:!

`git rebase -i HEAD~3`

Then you'll be on that view:
image

as explained in the blue part of that screenshot, you can either reword, drop, fixup, (etc) a commit.
`pick` is the default one which means "keep the commit as it is".

First (and oldest) one: `Add files via upload`, we want to reword it.
So we should have:
```
reword cad3673 Add files via upload
pick 6d462e2 Update README.md
pick ee9e380 WIP
```
*note that you'll have a different hash for the WIP commit*

Then we want to remove, to drop the commit updating the README:
So we should have:
```
reword cad3673 Add files via upload
drop 6d462e2 Update README.md
pick ee9e380 WIP
```

And finally, we want to merge the `WIP` into the previous commit (as `Update README.md` is dropped, previous commit at this stage will be `Add files via upload`).

So finally, we should have:
```
reword cad3673 Add files via upload
drop 6d462e2 Update README.md
fixup ee9e380 WIP
```

Then if you write quit in the terminal (if you have no idea how to do that just google it but it should be the same as when you do a commit if you don't use a GUI).

You'll be in a state where you see only the first commit name:
`Add files via upload`

Update that to: `style(logo): create logo and miniatures` and write quit again.

Then, you're done!

If you make a git log, you'll only have one commit :raised_hands: 

Now, you need to push your work but if you try to `git push` you'll be rejected.
It's because the history has changed, it's considered dangerous. Except that we know what we're doing in this branch is ok because nobody else is working on it, so we can safely push force: `git push -f`.

That's it, the merge request will be updated :wink: 

Let me know if you're lost somewhere or if you need further information.

**Comment by happyksu** [comment]
Hi Maxime!

Thank you but if you remember I'm designer and all you wrote me I still don't understand. I even download GitHub Desktop but...

I understand that you want everything to be perfect but you ask me to do something that I can not do.

May be it will be easier to delete my repository and create new one? Or something like that?

By the way I checked my files again and can say that I prepared png files with logo both with and without background and cropped (ready for use). Please, check again, may be you didn't noticed.

png folder:
PS_logo_high_res
PS_logo_low_res
PS_logo_monochrome_high_res
PS_logo_monochrome_low_res

**Comment by maxime1992** [comment]
Hi,

no worries at all :smile: 

I'll take a look to the changes you've made, indeed I didn't notice.

About the rebase, don't worry, I was trying to explain it to you as I've noticed on profile that you're looking to make contributions on Github and this is a common thing to do so I was more trying to help you rather than "getting something perfect" :smile_cat: If you make further modifications, just just them into a different commit and I'll manage the commits myself later before I merge ;)

**Comment by maxime1992** [comment]
Hey I was about to take a look to your updates but it seems that unfortunately you forgot to push =)

Latest update was 10 days ago on your side.

Let me know once you've pushed :+1:

**Comment by happyksu** [comment]
Hi!:)
Thank you for your help. I appreciate it! :) But it is harder than I thought. I hoped that to make graphic contribution will be enough to have design skills.
It seems you did not understand me. I said that I checked files that were already at Github.
Well, that doesn't matter 😄  Forget that and let's find out the way that will be comfortable for both of us.
I have two thoughts. I can delete my repository and make it from the begining. Or I can upload all files you need to Google Drive and you will manipulate with them as you wish (so I will not make a lot of mess in your project folders)
What do you think?

**Comment by maxime1992** [comment]
> It seems you did not understand me. I said that I checked files that were already at Github

I did understand you, but the fact is, your files were not modified since +10 days so you probably missed something.

Upload to drive and I'll handle the rest, thanks :smile:

**Comment by happyksu** [comment]
Hi!

Here is all files - https://drive.google.com/open?id=1bi6PX4RCZg7pS9b7rOEF63IZ0VRkN3j5

png - files with logo are presented in two versions (with and without background)
psd - logo and background on separate layers
sgv - all files witout background
vector - ai and eps files - editable

Hope now everything is ok 😄

**Comment by happyksu** [comment]
Hi!
Maxime, I'm still waiting for your answer)
Is everything alright? Will you use my design?

**Comment by maxime1992** [comment]
Hey @happyksu I was on holidays sorry about the delay.

I don't have access to the drive you shared. Can you put the link accessible to everyone please? :smiley_cat: 

Thanks

**Comment by happyksu** [comment]
Hi!
Try again https://drive.google.com/open?id=1bi6PX4RCZg7pS9b7rOEF63IZ0VRkN3j5

**Comment by maxime1992** [comment]
Hey @happyksu as we've talked about, I've taken over your PR :) 

Still, I've made the commit in your name and you're now marked as a contributor of Pizza-Sync :clap: 

Thanks a lot for the hard work and different iterations on the logo, I really like it :raised_hands: 

Good work!

**Comment by happyksu** [comment]
Hi @maxime1992 :)
Happy to hear that! It was nice to work on your logo design.
I wish you and your project good luck!

**Pull request closed without merging**
